steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/newsnow-backend', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/newsnow-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'newsnow-backend'
      - '--image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/newsnow-backend'
      - '--region=asia-northeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=3'
      - '--set-env-vars=DATABASE_URL=postgresql://neondb_owner:npg_9rQzCIoUfSV3@ep-curly-moon-aogf35qb-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require,OPENAI_API_KEY=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'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/newsnow-backend'
