import datetime
from typing import Optional

from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Text, UniqueConstraint, false
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base


class MarketCalendar(Base):
    """Per-date trading session or holiday override for an exchange.

    Rows are generated by the ReferenceCollector (or seed scripts) from the
    exchange's regular `sessions` + `trading_weekdays`, then adjusted for
    holidays / special sessions. freshness checks (REQUIREMENTS §39) read this
    table so that closed-market periods are not flagged as stale.
    """

    __tablename__ = "market_calendars"
    __table_args__ = (
        UniqueConstraint("exchange_id", "date", name="uq_market_calendars_exchange_date"),
    )

    exchange_id: Mapped[str] = mapped_column(
        Text, ForeignKey("exchanges.exchange_id"), primary_key=True
    )
    date: Mapped[datetime.date] = mapped_column(Date, primary_key=True)
    open_utc: Mapped[Optional[datetime.datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    close_utc: Mapped[Optional[datetime.datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    is_holiday: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=false())
