"""Initial data_sources registry (REQUIREMENTS §17, docs/DATA_SOURCES.md).

Compliance rule: external sources ship `enabled=false, terms_reviewed=false`
until reviewed in DATA_SOURCE_COMPLIANCE.md. `internal` sources are exempt —
they generate mock data for the dev loop (unblocks T06 without real vendors).
"""

from typing import Any

from sqlalchemy.orm import Session

from app.models.data_source import DataSource

SOURCES: list[dict[str, Any]] = [
    # ---- internal mock (dev loop; no external dependency, no licensing issue) ----
    {
        "source_id": "mock_market",
        "source_name": "Internal mock quote generator",
        "base_url": None,
        "data_type": "quote",
        "collection_type": "internal",
        "license_status": "internal",
        "robots_status": None,
        "terms_reviewed": True,
        "refresh_interval": 5,
        "delay_minutes": 0,
        "priority": 1,
        "enabled": True,
    },
    # ---- quotes: external (disabled pending review/license) ----
    {
        "source_id": "coinbase_market_api",
        "source_name": "Coinbase public market data",
        "base_url": "https://api.exchange.coinbase.com",
        "data_type": "quote",
        "collection_type": "api",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 5,
        "delay_minutes": 0,
        "priority": 10,
        "enabled": False,
    },
    {
        "source_id": "binance_market_api",
        "source_name": "Binance public market data",
        "base_url": "https://api.binance.com",
        "data_type": "quote",
        "collection_type": "api",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 5,
        "delay_minutes": 0,
        "priority": 20,
        "enabled": False,
    },
    {
        "source_id": "licensed_vendor_tbd",
        "source_name": "Licensed market data vendor (TBD)",
        "base_url": None,
        "data_type": "quote",
        "collection_type": "api",
        "license_status": "vendor_contract_required",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 15,
        "delay_minutes": 15,
        "priority": 5,
        "enabled": False,
    },
    {
        "source_id": "sse_szse_market",
        "source_name": "SSE/SZSE market data",
        "base_url": None,
        "data_type": "quote",
        "collection_type": "api",
        "license_status": "special_license_required",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 15,
        "delay_minutes": 15,
        "priority": 50,
        "enabled": False,
    },
    {
        "source_id": "ecb_reference_rates",
        "source_name": "ECB euro foreign exchange reference rates",
        "base_url": "https://data-api.ecb.europa.eu",
        "data_type": "quote",
        "collection_type": "api",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 86400,
        "delay_minutes": 1440,
        "priority": 60,
        "enabled": False,
    },
    {
        "source_id": "us_treasury_yields",
        "source_name": "US Treasury daily par yield curve",
        "base_url": "https://home.treasury.gov",
        "data_type": "quote",
        "collection_type": "api",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 86400,
        "delay_minutes": 1440,
        "priority": 60,
        "enabled": False,
    },
    # ---- news ----
    {
        "source_id": "fed_press_rss",
        "source_name": "Federal Reserve press releases RSS",
        "base_url": "https://www.federalreserve.gov/feeds/press_all.xml",
        "data_type": "news",
        "collection_type": "rss",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 300,
        "delay_minutes": 0,
        "priority": 10,
        "enabled": False,
    },
    {
        "source_id": "edgar_filings",
        "source_name": "SEC EDGAR filings",
        "base_url": "https://www.sec.gov/cgi-bin/browse-edgar",
        "data_type": "news",
        "collection_type": "api",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 300,
        "delay_minutes": 0,
        "priority": 20,
        "enabled": False,
    },
    {
        "source_id": "ecb_press_rss",
        "source_name": "ECB press releases RSS",
        "base_url": "https://www.ecb.europa.eu/rss/press.html",
        "data_type": "news",
        "collection_type": "rss",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 300,
        "delay_minutes": 0,
        "priority": 25,
        "enabled": False,
    },
    {
        "source_id": "boj_release_rss",
        "source_name": "Bank of Japan releases",
        "base_url": "https://www.boj.or.jp/en/rss/whatsnew.xml",
        "data_type": "news",
        "collection_type": "rss",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 600,
        "delay_minutes": 0,
        "priority": 25,
        "enabled": False,
    },
    # ---- calendar ----
    {
        "source_id": "mock_calendar",
        "source_name": "Internal mock economic calendar",
        "base_url": None,
        "data_type": "calendar",
        "collection_type": "internal",
        "license_status": "internal",
        "robots_status": None,
        "terms_reviewed": True,
        "refresh_interval": 3600,
        "delay_minutes": 0,
        "priority": 1,
        "enabled": True,
    },
    {
        "source_id": "bls_schedule",
        "source_name": "BLS release schedule",
        "base_url": "https://www.bls.gov",
        "data_type": "calendar",
        "collection_type": "api",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 3600,
        "delay_minutes": 0,
        "priority": 30,
        "enabled": False,
    },
    {
        "source_id": "central_bank_calendar",
        "source_name": "Central bank meeting calendars (Fed/ECB/BOJ/RBA)",
        "base_url": None,
        "data_type": "calendar",
        "collection_type": "api",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 3600,
        "delay_minutes": 0,
        "priority": 20,
        "enabled": False,
    },
    # ---- reference ----
    {
        "source_id": "iso10383_mic",
        "source_name": "ISO 10383 MIC list",
        "base_url": "https://www.iso20022.org",
        "data_type": "reference",
        "collection_type": "api",
        "license_status": "eval",
        "robots_status": None,
        "terms_reviewed": False,
        "refresh_interval": 604800,
        "delay_minutes": 0,
        "priority": 90,
        "enabled": False,
    },
]


def seed_data_sources(session: Session) -> int:
    """Idempotent upsert of the source registry. Returns row count."""
    for row in SOURCES:
        session.merge(DataSource(**row))
    return len(SOURCES)
