name: simplemarket
description: SimpleMarket — 简洁的全球行情资讯
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
